version: 0.0
os: linux
files:
  - source: /
    destination: /service/codedeploy2
permissions:
  - object: /
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
      #- location: /deploy/aws_samples/deregister_from_elb.sh
    - location: /deploy/start_maintenance.sh
  BeforeInstall:
    - location: /deploy/remove_app.sh
  AfterInstall:
    - location: /deploy/start_app.sh
      runas: ec2-user
  ApplicationStart:
    - location: /deploy/finish_maintenance.sh
      #- location: /deploy/aws_samples/register_with_elb.sh
